name: Bot de Extracción Diaria

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Ejecutar el script
        run: python prueba_auto.py

      - name: Guardar cambios en el repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add log_ejecucion.txt
          git commit -m "Actualización automática de log: $(date)" || exit 0
          git push
